apiVersion: v1
kind: Service
metadata:
    name: "settyl-e992"
    labels:
        app: "settyl-e992"
spec:
    type: LoadBalancer
    ports:
    - port: 5678
      targetPort: 5678
      protocol: TCP
      name: http
    selector:
        app: "settyl-e992"