apiVersion: v1
kind: Service
metadata:
    name: "workflow"
    labels:
        app: "workflow"
spec:
    type: ClusterIP
    ports:
    - port: 5678
      targetPort: 5678
      protocol: TCP
      name: http
    selector:
        app: "workflow"
