on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: phase1.azurecr.io
        username: ${{ secrets.acr_phase1_username }}
        password: ${{ secrets.acr_phase1_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/docker/images/settyl" -f  "docker/images/settyl/Dockerfile" -t phase1.azurecr.io/settyl:${{ github.sha }}
        docker push phase1.azurecr.io/settyl:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_settyl_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep settyl424d | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace settyl424d`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: settyl424d
        container-registry-url: phase1.azurecr.io
        container-registry-username: ${{ secrets.acr_phase1_username }}
        container-registry-password: ${{ secrets.acr_phase1_password }}
        secret-name: settyldockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: settyl424d
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          phase1.azurecr.io/settyl:${{ github.sha }}
        imagepullsecrets: |
          settyldockerauth